---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: foo
  labels:
    name: echoserver
    nitro.k8s.anjuna.io/managed: "yes"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
        nitro.k8s.anjuna.io/managed: "yes"
    spec:
      containers:
      - name: echoserver
        image: 171453223611.dkr.ecr.eu-west-2.amazonaws.com/echoserver
        imagePullPolicy: Always
        env:
          - name: ANJ_ENCLAVE_STREAM_CONSOLE
            value: "yes"
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2"
        ports:
          - containerPort: 5005

