apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: foo
spec:
  type: LoadBalancer
  selector:
    app: echoserver
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005



